package dev.mark.movieAPI;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "reviews")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Review {
    @Id
    private ObjectId id;
    private String body;
    // since ids are autogenerated we cannot pass an ID to this class
    // we need a custom constructor that takes only the body
    public Review(String body) {
        this.body = body;
    }
}
